### ISSUE TITLE
Error with get_census(geo_format = "sp")

### ISSUE THREAD

**Issue by pssguy** [mountainMath/cancensus#96] opened 2017-11-01 18:34 UTC
```r
 census_data_sp <- get_census(dataset='CA16', regions=list(CMA="59933"),
                          vectors=c("v_CA16_408","v_CA16_409","v_CA16_410"),
                           level='CSD', geo_format = "sp", use_cache = FALSE)
Querying CensusMapper API...
Downloading: 1.4 kB     Querying CensusMapper API...
Downloading: 25 kB     Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
```

The "sf" option does work

**Comment by atheriel** [comment] 2017-11-01 20:18
Is it possible for you to post the output of your `sessionInfo()`?

**Comment by atheriel** [comment] 2017-11-01 20:22
My hunch is that this is related to older versions of **rgdal**, which is used internally to parse the API response into an `sp` object. Try updating to a newer version of that package and see if things improve. We can update the required **rgdal** package version if so.

**Comment by pssguy** [comment] 2017-11-01 22:57
with only the cancensus library loaded

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2    cancensus_0.1.0 dplyr_0.7.4    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     knitr_1.17       bindr_0.1        magrittr_1.5     hms_0.3         
 [6] lattice_0.20-35  R6_2.2.2         rlang_0.1.2      httr_1.3.1       stringr_1.2.0   
[11] tools_3.4.2      rgdal_1.2-15     grid_3.4.2       htmltools_0.3.6  yaml_2.1.14     
[16] rprojroot_1.2    digest_0.6.12    assertthat_0.2.0 tibble_1.3.4     bookdown_0.5    
[21] readr_1.1.1      curl_3.0         glue_1.2.0       evaluate_0.10.1  rmarkdown_1.6   
[26] sp_1.2-5         stringi_1.1.5    compiler_3.4.2   backports_1.1.1  jsonlite_1.5    
[31] pkgconfig_2.0.1 

----

rgdal_1.2-15 is the most recent on CRAN . It was updated a couple of days ago. Perhaps that is the issue
This is first time I have used function with sp

**Comment by mountainMath** [comment] 2017-11-02 04:48
Headscratcher. I just updated from rgdal_1.2-8 to rgdal_1.2-15 and it works without a hitch.

**Comment by pssguy** [comment] 2017-11-02 14:34
The same error appeared as a  [tigris issue](https://github.com/walkerke/tigris/issues/16) if that helps

**Comment by pssguy** [comment] 2017-11-03 17:42
Even trying "switch computer off/on" did not resolve this for me

I'm actually wanting to use sp so that I can play around with [hexmapr](https://github.com/sassalley/hexmapr)

Is there a way to convert an sf download into a Large SpatialPolygonsdataFrame.? 
 I've tried one or two things without success but am not very knowledable in this area and am pretty sure there should be a way

**Comment by dshkol** [comment] 2017-11-03 17:58
Have you tried `as(x, "Spatial")` per https://cran.r-project.org/web/packages/sf/vignettes/sf2.html?

**Comment by pssguy** [comment] 2017-11-03 18:11
I actually did what I think is effectively equivalent
```
census_data_sf <- get_census(dataset='CA16', regions=list(CMA="59933"),
                          vectors=c("v_CA16_408","v_CA16_409","v_CA16_410"),
                          level='CSD', geo_format = "sf", use_cache = FALSE)
class(census_data_sf) #"sf"         "tbl_df"     "tbl"        "data.frame" #39 obs

sp <- as_Spatial(census_data_sf$geometry)
class(sp)
#[1] "SpatialPolygons"
#attr(,"package")
#[1] "sp"
length(x@polygons) #39
```
So I'm just falling down on coercing these two objects correctly
I'm sure it's simple - but then so am I

**Comment by atheriel** [comment] 2017-11-03 18:20
I doubt it's simple. It looks to be caused by confusion over the location of the downloaded geometry file, and is definitely a bug in our code, not yours.

I won't be able to try and reproduce this for a few days, but in the meantime you can try `debug(census_get)` and stepping through the function(s) manually. It's not too hard to debug misbehaving R code!

**Comment by pssguy** [comment] 2017-11-03 18:35
By simple, I meant combining the census_data_sf and sp objects - not the original issue!

the debugging confirms it occurs with rgdal
```
debug: geos <- rgdal::readOGR(geo_file, "OGRGeoJSON")
Browse[2]> 
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
```

I'll try some more uninstalling/installing again

**Comment by atheriel** [comment] 2017-11-03 20:44
When you're at the step right before the `geos = ...` line, what is the value of `geo_file`? Can you check that a file exists on your system at that location?

**Comment by atheriel** [comment] 2017-11-03 20:44
(To see the value of the variable, you can just type it into the debugger.)

**Comment by pssguy** [comment] 2017-11-03 20:52
@atherjel
Does this help
```
debug: geos <- rgdal::readOGR(geo_file, "OGRGeoJSON")
Browse[2]> 
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
> geo_file
Error: object 'geo_file' not found
```

**Comment by pssguy** [comment] 2017-11-03 20:57
@atheriel 
Here is the cache directory
![cache files](https://user-images.githubusercontent.com/2775918/32395559-dcbf5a66-c09e-11e7-836d-c027b33a0696.PNG)

**Comment by dshkol** [comment] 2017-11-12 20:10
@pssguy Was there a resolution to this or is this issue still happening?

**Comment by pssguy** [comment] 2017-11-14 20:47
@dshkol 
No joy. I tied on new laptop with freshly installed package and got same result
However, using the as() function as you suggested seems to coerce it fine. Thanks

**Comment by dshkol** [comment] 2017-11-15 21:49
Glad that you found a workaround but we'll keep this open to see if this happens for anyone else and try to reproduce it.

**Comment by mountainMath** [comment] 2017-11-18 06:05
What operating system are you using @pssguy? Maybe that will help reproduce it.

**Comment by dshkol** [comment] 2017-11-18 17:06
I'll try to reproduce on a win10 machine on Monday, but that's the only one I can get my hands on.

**Comment by pssguy** [comment] 2017-11-21 22:19
Thanks. I am on Windows 10

**Comment by dshkol** [comment] 2017-11-21 22:46
Reproduced with error on my work windows machine with only `cancensus` loaded and `rgdal` at 1.2-15 

```
census_data_sp <- get_census(dataset='CA16', regions=list(CMA="59933"),
+                              vectors=c("v_CA16_408","v_CA16_409","v_CA16_410"),
+                              level='CSD', geo_format = "sp", use_cache = FALSE)

Querying CensusMapper API...
Downloading: 1.4 kB     Querying CensusMapper API...
Downloading: 25 kB     Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
```

**Comment by dshkol** [comment] 2017-11-21 23:28
I've done a bit of testing and I can't get `rgdal` to open other geojson files, let alone the cached cancensus ones. I suspect there's an issue with how rgdal is processing layers in a geojson file. 

I've discovered a workaround that works, but I don't know if this is a workaround I want to code into cancensus until we figure out if this is an rgdal issues, a gdal issue, or a windows issue. Try replacing the layer name from "OGRGeoJSON" with the name of the geojson file excluding the extension, like the way you would read a shape file.

For example,  with `rgdal::readOGR("CM_geo_4a5626a6774fefc22c656038b44803a8.geojson", "CM_geo_4a5626a6774fefc22c656038b44803a8")`

**Comment by mountainMath** [comment] 2017-11-21 23:42
Or replacing
```{r}
geos <- rgdal::readOGR(geo_file, "OGRGeoJSON")
```
with
```{r}
layer_name=paste0("CM_geo_", digest::digest(param_string, algo = "md5"))
geos <- rgdal::readOGR(geo_file,layer_name)
```

(Not tested)

**Comment by atheriel** [comment] 2017-11-22 04:55
I am now hitting this bug as well. I think this might be related to [an API change in GDAL version 2.2](http://www.gdal.org/drv_geojson.html), which was released in mid-September:

> Starting with GDAL 2.2, the layer name is built with the following logic:
>
>    1. If a "name" member is found at the FeatureCollection level, it is used.
>    2. Otherwise if the filename is regular (ie not a URL with query parameters), then the filename without extension and path is used as the layer name.
>    3. Otherwise OGRGeoJSON is used.

It's possible that we're running afoul of these rules where we were not previously.

@dshkol, can you check your GDAL version (e.g. with `gdalinfo --version`)? I only have 2.2, and just want to confirm that it's not happening on 2.1.

Unless there's some compelling reason otherwise, I think that we should go with something like @mountainMath's solution, and just specify the layer name explicitly.

**Comment by atheriel** [comment] 2017-11-22 04:58
((If either of @mountainMath or @pssguy could confirm their GDAL version, that would also be helpful.)

Note that I don't mean the version of `rgdal`, but the underlying GDAL library itself.

**Comment by dshkol** [comment] 2017-11-22 05:00
> @dshkol, can you check your GDAL version (e.g. with gdalinfo --version)? I only have 2.2, and just want to confirm that it's not happening on 2.1.
1.11.3, but that doesn't matter because `rgdal` installs its own gdal if necessary. My rgdal connects to gdal 2.1.3, as is @mountainMath's. More importantly, @pssguy, my work machine, my home machine, and @mountainMath all used rgdal 1.2-15, so they should be using the same version of gdal under the hood.

I'm going to keep digging - I got in touch with an sp developer and I'll take some more detailed tests on my other computer tomorrow. 

Meanwhile, I'm putting together the final touches on a change to the base cancensus code that checks for this error and implements @mountainMath's suggestion. Should be ready in the next few mins.

**Comment by mountainMath** [comment] 2017-11-22 05:03
My underlying gdal is still 2.1.3, and I am not getting the error.

**Comment by mountainMath** [comment] 2017-11-22 05:04
If this is the new standard, we should probably make that the default and fall back on the old gdal version.

**Comment by dshkol** [comment] 2017-11-22 05:05
No, but you would if you tried the other way, I suspect. Here's a simple example to try and replicate:

In a clean session try:
```
library(rgdal)
download.file("https://www.mapbox.com/help/data/stations.geojson", "stations.geojson")
stations <- readOGR("stations.geojson", "OGRGeoJSON")
stations <- readOGR("stations.geojson", "stations")
```

**Comment by pssguy** [comment] 2017-11-22 05:09
@atheriel 
Sorry bit useless when comes to use of terminal (presumably) and cannot get info from there. Which directory do I run the gdalinfo -- version command from

I do have in win-library/3.4/sf/docker/gdal /Dockerfile
which inc text ...GDAL:

ENV GDAL_VERSION 2.2.2
ENV GDAL_VERSION_NAME 2.2.2

RUN wget ...
if that helps

**Comment by pssguy** [comment] 2017-11-22 18:22
@dshkol re your code above
```
Restarting R session...

> library(rgdal)
Loading required package: sp
rgdal: version: 1.2-15, (SVN revision 691)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.2.0, released 2017/04/28
 Path to GDAL shared files: C:/Users/Andrew/Documents/R/win-library/3.4/rgdal/gdal
 GDAL binary built with GEOS: TRUE 
 Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
 Path to PROJ.4 shared files: C:/Users/Andrew/Documents/R/win-library/3.4/rgdal/proj
 Linking to sp version: 1.2-5 
> download.file("https://www.mapbox.com/help/data/stations.geojson", "stations.geojson")
trying URL 'https://www.mapbox.com/help/data/stations.geojson'
Content type 'binary/octet-stream' length 29920 bytes (29 KB)
downloaded 29 KB

> stations <- readOGR("stations.geojson", "OGRGeoJSON")
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
> stations2 <- readOGR("stations.geojson", "stations")
OGR data source with driver: GeoJSON 
Source: "stations.geojson", layer: "stations"
with 86 features
It has 4 fields
```

**Comment by pssguy** [comment] 2017-11-22 18:42
@dshkol @atheriel 
Just confirming from my end that, with cancensus 0.1.5, get_census(geo_format='sp') works fine  
Thanks

**Comment by dshkol** [comment] 2017-11-22 18:54
@pssguy thanks. It's looking more and more that the case is a GDAL 2.2.0 API change. I've merged a patch to work around this. If you reinstall from github, your code should work now.

**Closed** 2017-11-22 18:57 UTC
Labels: bug
