### ISSUE TITLE
Broken file paths in get_statcan_geo_suite()

### ISSUE THREAD

**Issue by tomcardoso** [mountainMath/cancensus#204] opened 2024-01-04 04:12 UTC
I was just running `get_statcan_geo_suite` to grab dissemination blocks and ran into this error:

```sh
>>> Copying /Users/tcardoso/code/the 
ditto: /Users/tcardoso/Dropbox/code/the: No such file or directory

>>> Copying globe 
ditto: globe: No such file or directory

>>> Copying and 
ditto: and: No such file or directory
Error: '/Users/tcardoso/code/the globe and mail/project-folder/data/cache/geo_suite_2021/2021_92-150-X_eng/DB.csv' does not exist.
```

A long, long time ago, I made the bad decision to create this folder with spaces in the name, `the globe and mail`, and every once in a while it trips up like this due to those spaces. In this case, I suspect the issue is the `ditto` command on the following line:

https://github.com/mountainMath/cancensus/blob/40f4ba964d111df591c8a20105de5655a4429a39/R/geo_suite.R#L48

I imagine this could be fixed by quoting or escaping the spaces?

**Comment by mountainMath** [comment] 2024-01-05 01:25
Thanks for flagging. Can you install the current development branch with
```
remotes::install_github("mountainmath/cancensus@v0.5.7")
```
and check if that fixes the issue. (I believe it was caused by spaces in the file paths and the previous version not properly quoting files paths to account for that possibility.)

**Comment by tomcardoso** [comment] 2024-01-07 21:20
@mountainMath It works!

**Comment by mountainMath** [comment] 2024-01-08 00:39
Fixed in https://github.com/mountainMath/cancensus/pull/205

**Closed by mountainMath** 2024-01-08 00:39 UTC
